"""add anticlockwise

Revision ID: 0fa113150fe8
Revises: 4a809163498d
Create Date: 2021-03-21 09:02:25.930484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa113150fe8'
down_revision = '4a809163498d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('towerDB', sa.Column('anticlockwise', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('towerDB', 'anticlockwise')
    # ### end Alembic commands ###
