"""better user relation types

Revision ID: 0fb389a223b5
Revises: c74078a2084d
Create Date: 2020-05-03 13:33:11.702055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb389a223b5'
down_revision = 'c74078a2084d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tower_relation', sa.Column('creator', sa.Boolean(), nullable=True))
    op.add_column('user_tower_relation', sa.Column('recent', sa.Boolean(), nullable=True))
    op.add_column('user_tower_relation', sa.Column('visited', sa.DateTime(), nullable=True))
    with op.batch_alter_table('user_tower_relation') as batch_op:
        batch_op.drop_column('relationship')
        batch_op.drop_column('datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tower_relation', sa.Column('datetime', sa.DATETIME(), nullable=True))
    op.add_column('user_tower_relation', sa.Column('relationship', sa.VARCHAR(length=32), nullable=True))
    with op.batch_alter_table('user_tower_relation') as batch_op:
        batch_op.drop_column('visited')
        batch_op.drop_column('recent')
        batch_op.drop_column('creator')
    # ### end Alembic commands ###
