"""favorite tower relation

Revision ID: 157fdb8511bf
Revises: 7bb900e9c11c
Create Date: 2020-06-10 13:57:27.125734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157fdb8511bf'
down_revision = '7bb900e9c11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tower_relation', sa.Column('favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tower_relation', 'favorite')
    # ### end Alembic commands ###
