"""Add Wheatley columns to database

Revision ID: 18d1e622ccc5
Revises: fd24fcbb6ba6
Create Date: 2020-09-03 22:21:15.965629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d1e622ccc5'
down_revision = 'fd24fcbb6ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('towerDB', sa.Column('wheatley_enabled', sa.Boolean(), nullable=True))
    op.add_column('towerDB', sa.Column('wheatley_settings_json', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('towerDB', 'wheatley_settings_json')
    op.drop_column('towerDB', 'wheatley_enabled')
    # ### end Alembic commands ###
