"""track tower created date, user joined date

Revision ID: 22cc99c77bd3
Revises: ecf0969f42be
Create Date: 2020-06-24 19:05:28.199358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cc99c77bd3'
down_revision = 'ecf0969f42be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('towerDB', sa.Column('created_on', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('joined', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'joined')
    op.drop_column('towerDB', 'created_on')
    # ### end Alembic commands ###
