"""server field in TowerDB

Revision ID: 281165c8adae
Revises: fd24fcbb6ba6
Create Date: 2020-08-10 14:56:27.588992

"""
from alembic import op
import sqlalchemy as sa
from app import TowerDB, db


# revision identifiers, used by Alembic.
revision = '281165c8adae'
down_revision = 'fd24fcbb6ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('towerDB') as batch_op:
        batch_op.add_column(sa.Column('server',
                            sa.String(),
                            server_default='UK'))
    # for tower in TowerDB.query.all():
    #     tower.server = 'UK'
    # db.session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('towerDB') as batch_op:
        batch_op.drop_column('server')
    # ### end Alembic commands ###
