"""permitted servers

Revision ID: 5a2ff57bec91
Revises: 281165c8adae
Create Date: 2020-08-10 15:36:31.089766

"""
from alembic import op
import sqlalchemy as sa
from app import db, User


# revision identifiers, used by Alembic.
revision = '5a2ff57bec91'
down_revision = '281165c8adae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_permitted_servers',
                                    sa.String(length=128),
                                    server_default='UK,NA,SG'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('_permitted_servers')
    # ### end Alembic commands ###
