"""add anticlockwise

Revision ID: 62170879a8e6
Revises: 83e7dcb8df13
Create Date: 2021-03-28 10:44:36.285895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62170879a8e6"
down_revision = "83e7dcb8df13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("towerDB", sa.Column("anticlockwise", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("towerDB", "anticlockwise")
    # ### end Alembic commands ###
