"""new initial migration

Revision ID: 7bb900e9c11c
Revises: 
Create Date: 2020-06-02 14:19:25.958893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb900e9c11c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('towerDB',
    sa.Column('tower_id', sa.Integer(), nullable=False),
    sa.Column('tower_name', sa.String(length=32), nullable=True),
    sa.Column('last_access', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('tower_id')
    )
    op.create_index(op.f('ix_towerDB_tower_name'), 'towerDB', ['tower_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('user_tower_relation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tower_id', sa.Integer(), nullable=False),
    sa.Column('visited', sa.DateTime(), nullable=True),
    sa.Column('recent', sa.Boolean(), nullable=True),
    sa.Column('creator', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tower_id'], ['towerDB.tower_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tower_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tower_relation')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_towerDB_tower_name'), table_name='towerDB')
    op.drop_table('towerDB')
    # ### end Alembic commands ###
