"""fully muffled

Revision ID: 80634294e036
Revises: e08ac4aec4b1
Create Date: 2021-11-29 20:28:12.731749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "80634294e036"
down_revision = "e08ac4aec4b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("towerDB", sa.Column("fully_muffled", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("towerDB", "fully_muffled")
    # ### end Alembic commands ###
