"""patron columns in user

Revision ID: 83e7dcb8df13
Revises: 4a809163498d
Create Date: 2021-03-24 20:26:57.512428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e7dcb8df13'
down_revision = '4a809163498d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('donation_badge', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('donation_thank_you', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_donation_thank_you'), 'user', ['donation_thank_you'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_donation_thank_you'), table_name='user')
    op.drop_column('user', 'donation_thank_you')
    op.drop_column('user', 'donation_badge')
    # ### end Alembic commands ###
