"""towers table

Revision ID: b0f45183598a
Revises: 
Create Date: 2020-03-31 10:47:32.859041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f45183598a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('towerDB',
    sa.Column('tower_id', sa.Integer(), nullable=False),
    sa.Column('tower_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('tower_id')
    )
    op.create_index(op.f('ix_towerDB_tower_name'), 'towerDB', ['tower_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_towerDB_tower_name'), table_name='towerDB')
    op.drop_table('towerDB')
    # ### end Alembic commands ###
