"""track additional_sizes

Revision ID: b205dc2b730c
Revises: e1634351a997
Create Date: 2020-09-29 15:58:17.331486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b205dc2b730c'
down_revision = 'e1634351a997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('towerDB', sa.Column('additional_sizes_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('towerDB', 'additional_sizes_enabled')
    # ### end Alembic commands ###
