"""Track datetime in UserTowerRelation

Revision ID: c74078a2084d
Revises: 3947cc977d92
Create Date: 2020-05-02 21:38:16.757541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74078a2084d'
down_revision = '3947cc977d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tower_relation', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tower_relation', 'datetime')
    # ### end Alembic commands ###
