"""towerdb pk

Revision ID: c8efbb3b9f0e
Revises: 5a2ff57bec91
Create Date: 2020-08-11 14:34:02.734755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table


# revision identifiers, used by Alembic.
revision = 'c8efbb3b9f0e'
down_revision = '5a2ff57bec91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('towerDB', sa.Column('pk', sa.Integer()))

    print('FINISHED ADDING COLUMN')

    towerdb = table(
        'towerDB',
        sa.Column('pk', sa.Integer()),
        sa.Column('tower_id', sa.Integer()),
    )


    op.execute(
        towerdb.update().values({'pk': towerdb.c.tower_id})
    )

    print('FINISHED MIGRATING DATA')

    op.execute("PRAGMA foreign_keys = OFF;")
    op.execute("""
        CREATE TABLE temp_user_tower_relation(
            user_id INTEGER NOT NULL,
            tower_id INTEGER NOT NULL,
            visited DATETIME,
            recent BOOLEAN,
            creator BOOLEAN, bookmark BOOLEAN, host BOOLEAN,
            PRIMARY KEY (user_id, tower_id),
            CHECK (recent IN (0,1)),
            CHECK (creator IN (0,1)),
            CHECK (bookmark IN (0,1)),
            CHECK (host IN (0,1)),
            FOREIGN KEY(tower_id) REFERENCES "towerDB" (pk),
            FOREIGN KEY (user_id) REFERENCES user (id)
        );
               """)
    op.execute("INSERT INTO temp_user_tower_relation SELECT * FROM user_tower_relation;")
    op.execute("DROP TABLE user_tower_relation;")
    op.execute("ALTER TABLE temp_user_tower_relation RENAME TO user_tower_relation;")
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS "temp_towerDB" (
                pk INTEGER PRIMARY KEY AUTOINCREMENT,
                tower_id INTEGER NOT NULL,
                tower_name VARCHAR(32),
                last_access DATE NOT NULL,
                created_on DATE,
                host_mode_enabled BOOLEAN, server VARCHAR DEFAULT 'UK' NOT NULL,
                CHECK (host_mode_enabled IN (0, 1))
            );
        """)
    op.execute("""
               INSERT INTO temp_towerDB
               SELECT pk, tower_id, tower_name, last_access, created_on, host_mode_enabled, server
               FROM towerDB;""")
    op.execute("DROP TABLE towerDB;")
    op.execute("ALTER TABLE temp_towerDB RENAME TO towerDB;")
    op.execute("PRAGMA foreign_keys = ON;")

    op.create_index(op.f('ix_towerDB_tower_id'), 'towerDB', ['tower_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.execute("PRAGMA foreign_keys = OFF;")
    op.execute("""
        CREATE TABLE temp_user_tower_relation(
            user_id INTEGER NOT NULL,
            tower_id INTEGER NOT NULL,
            visited DATETIME,
            recent BOOLEAN,
            creator BOOLEAN, bookmark BOOLEAN, host BOOLEAN,
            PRIMARY KEY (user_id, tower_id),
            CHECK (recent IN (0,1)),
            CHECK (creator IN (0,1)),
            CHECK (bookmark IN (0,1)),
            CHECK (host IN (0,1)),
            FOREIGN KEY(tower_id) REFERENCES "towerDB" (tower_id),
            FOREIGN KEY (user_id) REFERENCES user (id)
        );
               """)
    op.execute("INSERT INTO temp_user_tower_relation SELECT * FROM user_tower_relation;")
    op.execute("DROP TABLE user_tower_relation;")
    op.execute("ALTER TABLE temp_user_tower_relation RENAME TO user_tower_relation;")
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS "temp_towerDB" (
                tower_id INTEGER PRIMARY KEY,
                tower_name VARCHAR(32),
                last_access DATE NOT NULL,
                created_on DATE,
                host_mode_enabled BOOLEAN, server VARCHAR DEFAULT 'UK' NOT NULL,
                CHECK (host_mode_enabled IN (0, 1))
            );
        """)
    op.execute("""
               INSERT INTO temp_towerDB
               SELECT tower_id, tower_name, last_access, created_on, host_mode_enabled, server
               FROM towerDB;
               """)
    op.execute("DROP TABLE towerDB;")
    op.execute("ALTER TABLE temp_towerDB RENAME TO towerDB;")
    op.execute("PRAGMA foreign_keys = ON;")


    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    # ### end Alembic commands ###
