"""cowbell setting

Revision ID: e08ac4aec4b1
Revises: 5c377448c068
Create Date: 2021-04-14 08:06:29.484160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e08ac4aec4b1"
down_revision = "5c377448c068"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("towerDB", sa.Column("cowbell_enabled", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("towerDB", "cowbell_enabled")
    # ### end Alembic commands ###
