"""add host column

Revision ID: ecf0969f42be
Revises: 157fdb8511bf
Create Date: 2020-06-11 08:39:47.620975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf0969f42be'
down_revision = '157fdb8511bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tower_relation', sa.Column('host', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tower_relation', 'host')
    # ### end Alembic commands ###
