"""last_access date in TowerDB

Revision ID: efc3048c54ef
Revises: b0f45183598a
Create Date: 2020-04-21 11:45:24.548902

"""
from alembic import op
import sqlalchemy as sa
from datetime import date


# revision identifiers, used by Alembic.
revision = 'efc3048c54ef'
down_revision = 'b0f45183598a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('towerDB', sa.Column('last_access', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('towerDB', 'last_access')
    # ### end Alembic commands ###
