"""add last_access on towerDB

Revision ID: fb94a34382a8
Revises: b0f45183598a
Create Date: 2020-04-21 12:10:01.397108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb94a34382a8'
down_revision = 'b0f45183598a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('towerDB', sa.Column('last_access', sa.Date(), nullable=True))
    op.execute('UPDATE towerDB SET last_access = date()')
    with op.batch_alter_table('towerDB') as batch_op:
        batch_op.alter_column('last_access',nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('towerDB') as batch_op:
        batch_op.drop_column('last_access')
    # ### end Alembic commands ###
