"""host mode enabled

Revision ID: fd24fcbb6ba6
Revises: 22cc99c77bd3
Create Date: 2020-06-27 13:45:42.123961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd24fcbb6ba6'
down_revision = '22cc99c77bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('towerDB', sa.Column('host_mode_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('towerDB') as batch_op:
        batch_op.drop_column('host_mode_enabled')
    # ### end Alembic commands ###
